# import stuff
from snakemake.utils import R
from os.path import join
from os import listdir
import os, sys

# Global workflow variables
configfile: 'config/config.yaml'              # config dictionary
#common.smk already defines
#samples, samplesdf
#tools
#project

include: "rules/common.smk"
include: "rules/other.smk"

# convert = {'Y': False, 'N': True}
if config['basecalling'].startswith("Y"):
    basecalling = True
else:
    basecalling = False

# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
# singularity: "docker://continuumio/miniconda3"


rule all:
    input:
        expand(join(workdir,fastqs,"{sample}.fastq.gz"), sample=samples)


if basecalling:
    include: "rules/basecalling.smk"


