#you most probably dont need to change these
tools: "config/tools.tsv"
# you probably need to change these
samples: "config/samples.tsv"
workdir: "/path/to/workdir"
basecalling: "Y"
flowcell: "FLO-MIN106"
kit: "SQK-RNA001"